export  enum Configuration {
    SSL = 'SSL',
    PORT = 'PORT',
    TYPE='TYPE',
    HOST='HOST',
    PORTDB= 'PORTDB',
    USERNAME='USERNAME',
    PASSWORD='PASSWORD',
    DATABASE='DATABASE',
    TYPEORM_MIGRATIONS_DIR="TYPEORM_MIGRATIONS_DIR",
}